---
name: CI Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cachix-release:
    name: Cachix releaser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: mycache
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}" # FIXME: Needs to be filled in.
      - name: Run build
        run: nix build
